package openwrestling.model.constants;

import java.util.Arrays;
import java.util.List;

public class Words {

    public final static List<String> ACTIVITIES = Arrays.asList(
            "ATV racing",
            "Abseiling",
            "Aid climbing",
            "Air racing",
            "Alpine skiing",
            "Amateur wrestling",
            "Angling",
            "Apnoea finswimming",
            "Arm wrestling",
            "Artistic cycling",
            "Auto racing",
            "Axe throwing",
            "BASE jumping",
            "Backpacking",
            "Banger racing",
            "Banzai skydiving",
            "Bareback Bronc Riding",
            "Barrel Racing",
            "Barrel jumping",
            "Barrel racing",
            "Basque traditional weightlifting",
            "Baton twirling",
            "Beagling",
            "Benchrest shooting",
            "Big game hunting",
            "Big-game fishing",
            "Board track racing",
            "Bodyboarding",
            "Bodybuilding",
            "Boffer fighting",
            "Bouldering",
            "Bowling",
            "Boxing",
            "Breakaway Roping",
            "Bronc Riding",
            "Bullriding",
            "Bungee jumping",
            "Bushwhacking",
            "Calf Roping",
            "Campdrafting",
            "Canoeing",
            "Canyoning",
            "Card stacking",
            "Casterboarding",
            "Casting",
            "Catch wrestling",
            "Chariot racing",
            "Cheerleading",
            "Chess boxing",
            "Clay pigeon shooting",
            "Cliff diving",
            "Climbing",
            "Cluster ballooning",
            "Coastal and ocean rowing",
            "Coasteering",
            "Cockfighting",
            "Competitive dancing",
            "Competitive eating",
            "Competitive swimming",
            "Cornish hurling",
            "Cornish wrestling",
            "Cowboy action shooting",
            "Creeking",
            "Cross-country mountain biking",
            "Cross-country running",
            "Cross-country skiing",
            "Curling",
            "Cycling",
            "Deep-water soloing",
            "Deer hunting",
            "Desert racing",
            "Dice stacking",
            "Dinghy sailing",
            "Dirt jumping",
            "Dirt track racing",
            "Diving",
            "Downhill mountain biking",
            "Drag boat racing",
            "Drag racing",
            "Dragon boat racing",
            "Dressage",
            "Drifting",
            "Egyptian stick fencing",
            "Endurance racing",
            "Endurance riding",
            "Equestrian vaulting",
            "Extreme ironing",
            "F1 powerboat racing",
            "Fell running",
            "Fencing",
            "Ferret legging",
            "Figure skating",
            "Fishing",
            "Fly fishing",
            "Flying trapeze",
            "Folk wrestling",
            "Formula racing",
            "Fox hunting",
            "Free running",
            "Freeboating",
            "Freediving",
            "Freestyle skiing",
            "Freestyle swimming",
            "Freestyle wrestling",
            "Geocaching",
            "Gig racing",
            "Gliding",
            "Goat Tying",
            "Grand Prix motorcycle racing",
            "Grappling",
            "Greco-Roman wrestling",
            "Greek wrestling",
            "Haggis hurling",
            "Hang gliding",
            "Hare coursing",
            "Harness racing",
            "Hiking",
            "Hillclimbing",
            "Hopper ballooning",
            "Horse racing",
            "Horseshoe throwing",
            "Hot Air Balloon Racing",
            "Hot air ballooning",
            "Hurling",
            "Hydroplane racing",
            "Ice climbing",
            "Ice dancing",
            "Ice fishing",
            "Ice racing",
            "Ice yachting",
            "Immersion finswimming",
            "Jet sprint boat racing",
            "Jousting",
            "Juggling",
            "Jumping",
            "Kart racing",
            "Kayaking",
            "Kickboxing",
            "Kite fighting",
            "Kite flying",
            "Kite landboarding",
            "Kiteboarding",
            "Kitesurfing",
            "Kneeboarding",
            "Knife throwing",
            "Lancashire wrestling",
            "Land sailing",
            "Land windsurfing",
            "Legends car racing",
            "Letterboxing",
            "Logrolling",
            "Metallic silhouette shooting",
            "Midget car racing",
            "Miniature Bull Riding",
            "Mixed climbing",
            "Mongolian wrestling",
            "Motorboat racing",
            "Motorcycle drag racing",
            "Motorcycle racing",
            "Mountain running",
            "Mountain unicycling",
            "Mountainboarding",
            "Mountaineering",
            "Mud bogging",
            "Nguni stick-fighting",
            "Noodling",
            "Nordic skiing",
            "Object spinning",
            "Off-road racing",
            "Off-roading",
            "Offshore powerboat racing",
            "Olympic weightlifting",
            "Orienteering",
            "Outrigger canoeing",
            "Paddleboarding",
            "Padiddling",
            "Pair skating",
            "Parachuting",
            "Paragliding",
            "Paramotoring",
            "Parasailing",
            "Pickup truck racing",
            "Plate spinning",
            "Pole bending",
            "Pole climbing",
            "Powerbocking",
            "Powered paragliding",
            "Powerlifting",
            "Practical shooting",
            "Production car racing",
            "RC racing",
            "Racewalking",
            "Rafting",
            "Rallying",
            "Reining",
            "Ring-goal",
            "Ringball",
            "Ringette",
            "Riverboarding",
            "Road bicycle racing",
            "Road racing",
            "Road running",
            "Rock climbing",
            "Rock fishing",
            "Rogaining",
            "Rope climbing",
            "Rope jumping",
            "Roping",
            "Rowing",
            "Running",
            "Saddle Bronc Riding",
            "Sailing",
            "Sandboarding",
            "Scootering",
            "Scuba diving",
            "Sea kayaking",
            "Shoot boxing",
            "Shootfighting",
            "Shooting",
            "Short track motor racing",
            "Show jumping",
            "Single skating",
            "Skateboarding",
            "Skeet shooting",
            "Ski flying",
            "Ski jumping",
            "Ski touring",
            "Skiboarding",
            "Skibobbing",
            "Skiing",
            "Skijoring",
            "Skimboarding",
            "Skydiving",
            "Skyrunning",
            "Skysurfing",
            "Slacklining",
            "Slot car racing",
            "Snorkelling",
            "Snow kiting",
            "Snowboarding",
            "Snowkiting",
            "Snowmobile racing",
            "Snowshoe running",
            "Spearfishing",
            "Speed skiing",
            "Sport climbing",
            "Sport diving",
            "Sport fishing",
            "Sport kite",
            "Sport stacking",
            "Sports car racing",
            "Sprint car racing",
            "Squirt boating",
            "Stacking",
            "Stand up paddle boarding",
            "Steer Roping",
            "Steer Wrestling",
            "Still rings",
            "Stock car racing",
            "Street racing",
            "Street unicycling",
            "Streetboarding",
            "Superbike racing",
            "Supersport racing",
            "Surf fishing",
            "Surf kayaking",
            "Surface finswimming",
            "Surfing",
            "Swimming",
            "Sword fighting",
            "Synchronized swimming",
            "TT racing",
            "Target shooting",
            "Team Roping",
            "Team penning",
            "Telemark skiing",
            "Tent pegging",
            "Throwing",
            "Thumb wrestling",
            "Toe wrestling",
            "Touring car racing",
            "Tournament of Knights",
            "Tower running",
            "Track cycling",
            "Track racing",
            "Tractor pulling",
            "Traditional climbing",
            "Trail running",
            "Trampolining",
            "Trap shooting",
            "Truck racing",
            "Tumbling",
            "Underwater cycling",
            "Underwater orienteering",
            "Underwater target shooting",
            "Underwater wrestling",
            "Unicycling",
            "Vintage racing",
            "Wakeboarding",
            "Wakesurfing",
            "Walking",
            "Waymarking",
            "Weightlifting",
            "Wheelchair racing",
            "White water rafting",
            "Whitewater kayaking",
            "Wife-carrying",
            "Windsurfing",
            "Wing Chun",
            "Wingsuit flying",
            "Wolf hunting",
            "Wood chopping",
            "Wood splitting",
            "Wrestling",
            "Yoyoing"
    );

    public final static List<String> BODY_PARTS = Arrays.asList(
            "Adam's apple",
            "adenoids",
            "adrenal gland",
            "anatomy",
            "ankle",
            "anus",
            "appendix",
            "arch",
            "arm",
            "artery",
            "back",
            "ball of the foot",
            "belly",
            "belly button",
            "big toe",
            "bladder",
            "blood",
            "blood vessels",
            "body",
            "bone",
            "brain",
            "breast",
            "buttocks",
            "calf",
            "capillary",
            "carpal",
            "cartilage",
            "cell",
            "cervical vertebrae",
            "cheek",
            "chest",
            "chin",
            "circulatory system",
            "clavicle",
            "coccyx",
            "collar bone",
            "diaphragm",
            "digestive system",
            "ear",
            "ear lobe",
            "elbow",
            "endocrine system",
            "esophagus",
            "eye",
            "eyebrow",
            "eyelashes",
            "eyelid",
            "face",
            "fallopian tubes",
            "feet",
            "femur",
            "fibula",
            "filling",
            "finger",
            "fingernail",
            "follicle",
            "foot",
            "forehead",
            "gallbladder",
            "glands",
            "groin",
            "gums",
            "hair",
            "hand",
            "head",
            "heart",
            "heel",
            "hip",
            "humerus",
            "immune system",
            "index finger",
            "instep",
            "intestines",
            "iris",
            "jaw",
            "kidney",
            "knee",
            "larynx",
            "leg",
            "ligament",
            "lip",
            "liver",
            "lobe",
            "lumbar vertebrae",
            "lungs",
            "lymph node",
            "mandible",
            "metacarpal",
            "metatarsal",
            "molar",
            "mouth",
            "muscle",
            "nail",
            "navel",
            "neck",
            "nerves",
            "nipple",
            "nose",
            "nostril",
            "organs",
            "ovary",
            "palm",
            "pancreas",
            "patella",
            "pelvis",
            "phalanges",
            "pharynx",
            "pinky",
            "pituitary",
            "pore",
            "pupil",
            "radius",
            "rectum",
            "red blood cells",
            "respiratory system",
            "ribs",
            "sacrum",
            "scalp",
            "scapula",
            "senses",
            "shin",
            "shoulder",
            "shoulder blade",
            "skeleton",
            "skin",
            "skull",
            "sole",
            "spinal column",
            "spinal cord",
            "spine",
            "spleen",
            "sternum",
            "stomach",
            "tarsal",
            "teeth",
            "tendon",
            "testes",
            "thigh",
            "thorax",
            "throat",
            "thumb",
            "thyroid",
            "tibia",
            "tissue",
            "toe",
            "toenail",
            "tongue",
            "tonsils",
            "tooth",
            "torso",
            "trachea",
            "ulna",
            "ureter",
            "urethra",
            "urinary system",
            "uterus",
            "uvula",
            "vein",
            "vertebra",
            "waist",
            "white blood cells",
            "wrist"
    );

}
